/**
 * Version and command surface for the model-management tool set.
 *
 * This plugin has no CLI; its "commands" are the five tools the model can call.
 * Stating them in one place lets a deployment answer "what can this plugin do?"
 * without reading the registration code, and pins the version so the model-facing
 * surface cannot drift from a release.
 *
 * @module dsh-multi-model-provider
 */
/** Package version; asserted equal to package.json by the contract tests. */
export declare const VERSION = "0.1.0-rc.9";
/** Every model-callable tool name, in registration order. */
export declare const TOOL_NAMES: ("list_model_routes" | "configure_model_route" | "inspect_volcengine_provider" | "select_volcengine_language_models" | "list_task_models" | "discover_task_models" | "select_task_models" | "register_task_model" | "prepare_model_portraits" | "get_model_portrait" | "upsert_model_portrait" | "validate_model_portrait" | "invoke_task_model" | "summarize_model_usage" | "select_default_model")[];
/** Discoverable summary of the tool set and the two registration paths. */
export declare const HELP = "multi-model-provider 0.1.0-rc.9\n\nTwo deliberately separate registration paths. Language/chat models stay owned by\nllm-pi-ai; non-language task models live in this plugin's own catalog.\n\nlanguage / chat models:\n  list_model_routes        inspect routes, credential status, and model catalogs\n  configure_model_route    create or update one llm-pi-ai provider profile\n  inspect_volcengine_provider inspect Ark/Doubao credentials, live catalog, selections, and usage paths\n  select_volcengine_language_models replace Ark language/VLM selection; [] disables all\n  select_default_model     save the default model for newly created Agents\n\nnon-language task models (image, speech, audio, video, realtime, embedding, reranking):\n  list_task_models         inspect registrations and whether they are callable\n  discover_task_models     query an authenticated provider model catalog\n  select_task_models       replace the enabled set; [] disables all\n  register_task_model      create or update a registration and its connection\n  prepare_model_portraits  expand one short intent into the complete portrait workflow\n  get_model_portrait       inspect price, strengths, speed, I/O, and evidence\n  upsert_model_portrait    save an evidence-backed router-facing portrait\n  validate_model_portrait  check registration, evidence, credentials, and adapter\n  invoke_task_model        execute one registered operation through its adapter\n  summarize_model_usage    aggregate current-session invocation observations\n\ncredentials:\n  Registration tools accept only reference names such as OPENAI_API_KEY. A\n  multi-credential provider may use named refs such as DOUBAO_APPID and\n  DOUBAO_TOKEN. They never accept an API key value. When a reference is not configured, direct\n  the user to the secure Settings credential field; never ask for a key in chat.\n\nregistration is not callability:\n  A task-model registration is catalog metadata until a compatible runtime\n  adapter is installed. list_task_models reports the two states separately.\n  Disabled registrations remain inspectable but cannot be routed or invoked.\n\nprovider discovery and selection:\n  Volcengine is one provider connection spanning Ark and Doubao products while\n  each product keeps its own credential slots. Discovery is advisory and never\n  auto-registers or auto-enables returned models. An empty enabled selection is\n  preserved as all disabled; it never falls back to all models.\n\nportrait workflow:\n  \u201C\u6574\u7406\u521D\u59CB\u753B\u50CF\u201D is sufficient: the Agent calls prepare_model_portraits, gathers\n  authoritative facts, saves each portrait, and validates it automatically.\n  Native LLM and task invocation events record metrics but never content or credentials.\n";
//# sourceMappingURL=help.d.ts.map